version: '3.8'

services:
  portfolio:
    build: .
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./:/usr/share/nginx/html
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge
